# updated dvc.yaml

stages:
  data_ingestion:
    cmd: python -m src_files.data_processing.data_ingestion
    deps:
    - src_files/data_processing/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python -m src_files.data_processing.data_preprocessing
    deps:
    - data/raw
    - src_files/data_processing/data_preprocessing.py
    outs:
    - data/processed

  model_building:
    cmd: python -m src_files.model.model_building
    deps:
    - data/processed
    - src_files/model/model_building.py
    outs:
    - models/education_loan_model.pkl

  model_evaluation:
    cmd: python -m src_files.model.model_evaluation
    deps:
    - models/education_loan_model.pkl
    - src_files/model/model_evaluation.py
    metrics:
    - reports/metrics.json
    outs:
    - reports/experiment_info.json  # Add the model_info.json file as an output

  model_registration:
    cmd: python -m src_files.model.register_model
    deps:
    - reports/experiment_info.json
    - src_files/model/register_model.py